=== RafaelAmauri/Arquitetura-de-Computadores-3/Amnesia/Amnesia_jar/Configuration/amnesia.dtd
<!ELEMENT AmnesiaConfiguration (Processor,Trace,CPU, MainMemory, Cache*, VirtualMemory?)>

        <!--AMNESIA CONFIGURABLE MODULES -->
        <!ELEMENT Processor (processorContains, createTraceFile)>
        <!ELEMENT Trace (wordSize)>
        <!ELEMENT CPU (wordSize)>
        <!ELEMENT MainMemory (blockSize, memorySize, ciclesPerAccessRead, ciclesPerAccessWrite, timeCicle, ciclesPerAccess)>
        <!ELEMENT Cache (cacheType, ((instructionCache, dataCache) | (unifiedCache)))*>
        <!ELEMENT VirtualMemory (pageSize, diskMemorySize, diskCiclesPerAccess,diskCiclesPerAccessWrite,diskCiclesPerAccessRead, timeCicle,pageTableReplacementAlgorithm, TLBType, ((instructionTLB, dataTLB)|unifiedTLB)?)>


        <!--CACHE CONFIGURABLE ELEMENTS -->
        <!ELEMENT instructionCache (lineSize, ciclesPerAccess,ciclesPerAccessRead, ciclesPerAccessWrite, timeCicle, memorySize, associativityLevel, writePolicy, replacementAlgorithm)>
        <!ELEMENT dataCache (lineSize, ciclesPerAccess,ciclesPerAccessRead, ciclesPerAccessWrite, timeCicle, memorySize, associativityLevel, writePolicy, replacementAlgorithm)>
        <!ELEMENT unifiedCache (lineSize, ciclesPerAccess,ciclesPerAccessRead, ciclesPerAccessWrite, timeCicle, memorySize, associativityLevel, writePolicy, replacementAlgorithm)>

        <!ELEMENT instructionTLB ( ciclesPerAccess, ciclesPerAccessRead, ciclesPerAccessWrite, timeCicle,memorySize, replacementAlgorithm)>
        <!ELEMENT dataTLB ( ciclesPerAccess,ciclesPerAccessRead, ciclesPerAccessWrite, timeCicle, memorySize, replacementAlgorithm)>
        <!ELEMENT unifiedTLB ( ciclesPerAccess,ciclesPerAccessRead, ciclesPerAccessWrite, timeCicle, memorySize, replacementAlgorithm)>


        <!--DATA TYPE -->
        <!ELEMENT cacheType (#PCDATA)>

        <!ELEMENT blockSize (#PCDATA)>
        <!ELEMENT wordSize (#PCDATA)>
        <!ELEMENT lineSize (#PCDATA)>
        <!ELEMENT ciclesPerAccess (#PCDATA)>
        <!ELEMENT memorySize (#PCDATA)>
        <!ELEMENT associativityLevel (#PCDATA)>
        <!ELEMENT writePolicy (#PCDATA)>
        <!ELEMENT replacementAlgorithm (#PCDATA)>
        <!ELEMENT pageSize (#PCDATA)>
        <!ELEMENT diskMemorySize (#PCDATA)>
        <!ELEMENT registerOffset (#PCDATA)>
        <!ELEMENT TLBType (#PCDATA)>
        <!ELEMENT pageTableReplacementAlgorithm (#PCDATA)>

        <!ELEMENT processorContains (#PCDATA)>
        <!ELEMENT createTraceFile (#PCDATA)>
        <!ELEMENT ciclesPerAccessRead (#PCDATA)>
        <!ELEMENT ciclesPerAccessWrite (#PCDATA)>
        <!ELEMENT timeCicle (#PCDATA)>
        <!ELEMENT diskCiclesPerAccess (#PCDATA)>
        <!ELEMENT diskCiclesPerAccessRead (#PCDATA)>
        <!ELEMENT diskCiclesPerAccessWrite (#PCDATA)>

=== RafaelAmauri/Arquitetura-de-Computadores-3/Amnesia/Amnesia_jar/Arquiteturas/Archbase-LRU (copy).xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE AmnesiaConfiguration SYSTEM "Configuration/amnesia.dtd">
<?xml-stylesheet type="text/css" href="teste.css"?>
<AmnesiaConfiguration>
    <Processor>
        <processorContains>0</processorContains>
        <createTraceFile>0</createTraceFile>
    </Processor>
    <Trace>
        <wordSize>4</wordSize>
    </Trace>
    <CPU>
        <wordSize>4</wordSize>
    </CPU>
    <MainMemory>
        <blockSize>2</blockSize>
        <memorySize>16</memorySize>
        <ciclesPerAccessRead>1</ciclesPerAccessRead>
        <ciclesPerAccessWrite>2</ciclesPerAccessWrite>
        <timeCicle>10</timeCicle>
    </MainMemory>
	<Cache>
        <cacheType>Unified</cacheType>
        <unifiedCache>
            <lineSize>2</lineSize>
            <ciclesPerAccessRead>1</ciclesPerAccessRead>
            <ciclesPerAccessWrite>2</ciclesPerAccessWrite>
            <timeCicle>1</timeCicle>
            <memorySize>16</memorySize>
            <associativityLevel>8</associativityLevel>
            <writePolicy>WriteThrough</writePolicy>
            <replacementAlgorithm>FIFO</replacementAlgorithm>
        </unifiedCache>
    </Cache>
	<VirtualMemory>
        <pageSize>4</pageSize>
        <diskMemorySize>16</diskMemorySize>
        <diskCiclesPerAccessRead>1</diskCiclesPerAccessRead>
        <diskCiclesPerAccessWrite>2</diskCiclesPerAccessWrite>
        <timeCicle>100</timeCicle>
        <pageTableReplacementAlgorithm>FIFO</pageTableReplacementAlgorithm>
        
		<TLBType>unified</TLBType>
		<unifiedTLB>
			<memorySize>2</memorySize>
			<ciclesPerAccessRead>1</ciclesPerAccessRead>
			<ciclesPerAccessWrite>2</ciclesPerAccessWrite>
			<timeCicle>1</timeCicle>
			<replacementAlgorithm>FIFO</replacementAlgorithm>
		</unifiedTLB>
	</VirtualMemory>
</AmnesiaConfiguration>
